# 插件名称。
name: PocketProbe

# 插件版本。
version: 1.5.2

# 插件主类。
main: org.YanPl.pocketProbe.PocketProbe

# API 版本。
api-version: 1.18

# 命令定义。
commands:
  pocketprobe:
    description: 打开另一个玩家的背包进行检查和编辑。
    usage: /<command> <玩家名>
    permission: pocketprobe.use
    permission-message: 你没有权限使用此命令。
    aliases: [pp]

# 权限定义。
permissions:
  pocketprobe.use:
    description: 允许玩家使用 /pocketprobe 命令查看和编辑背包。
    default: op